export interface CategorySeed {
  code: string;
  nameEn: string;
  nameEs: string;
  nameEl: string;
  color?: string;
  icon?: string;
  depth: number;
  parentCode?: string;
}

export const SYSTEM_CATEGORIES: CategorySeed[] = [
  // Root categories (depth 0)
  {
    code: "operating",
    nameEn: "Operating Expenses",
    nameEs: "Gastos Operativos",
    nameEl: "Λειτουργικά Έξοδα",
    color: "#4EDEA3",
    icon: "business_center",
    depth: 0,
  },
  {
    code: "professional",
    nameEn: "Professional Services",
    nameEs: "Servicios Profesionales",
    nameEl: "Επαγγελματικές Υπηρεσίες",
    color: "#60A5FA",
    icon: "gavel",
    depth: 0,
  },
  {
    code: "technology",
    nameEn: "Technology",
    nameEs: "Tecnologia",
    nameEl: "Τεχνολογία",
    color: "#A78BFA",
    icon: "devices",
    depth: 0,
  },
  {
    code: "travel",
    nameEn: "Travel & Transport",
    nameEs: "Viajes y Transporte",
    nameEl: "Ταξίδια & Μεταφορές",
    color: "#F59E0B",
    icon: "flight",
    depth: 0,
  },
  {
    code: "financial",
    nameEn: "Financial",
    nameEs: "Financiero",
    nameEl: "Χρηματοοικονομικά",
    color: "#EF4444",
    icon: "account_balance",
    depth: 0,
  },
  {
    code: "other",
    nameEn: "Other",
    nameEs: "Otros",
    nameEl: "Άλλα",
    color: "#6B7280",
    icon: "more_horiz",
    depth: 0,
  },

  // Child categories (depth 1)
  {
    code: "operating.rent",
    nameEn: "Rent",
    nameEs: "Alquiler",
    nameEl: "Ενοίκιο",
    depth: 1,
    parentCode: "operating",
  },
  {
    code: "operating.utilities",
    nameEn: "Utilities",
    nameEs: "Servicios Públicos",
    nameEl: "Κοινόχρηστα",
    depth: 1,
    parentCode: "operating",
  },
  {
    code: "operating.telecommunications",
    nameEn: "Telecommunications",
    nameEs: "Telecomunicaciones",
    nameEl: "Τηλεπικοινωνίες",
    depth: 1,
    parentCode: "operating",
  },
  {
    code: "operating.office_supplies",
    nameEn: "Office Supplies",
    nameEs: "Material de Oficina",
    nameEl: "Γραφική Ύλη",
    depth: 1,
    parentCode: "operating",
  },
  {
    code: "operating.insurance",
    nameEn: "Insurance",
    nameEs: "Seguros",
    nameEl: "Ασφάλιση",
    depth: 1,
    parentCode: "operating",
  },
  {
    code: "operating.marketing",
    nameEn: "Marketing",
    nameEs: "Marketing",
    nameEl: "Μάρκετινγκ",
    depth: 1,
    parentCode: "operating",
  },
  {
    code: "operating.training",
    nameEn: "Training & Education",
    nameEs: "Formacion",
    nameEl: "Εκπαίδευση",
    depth: 1,
    parentCode: "operating",
  },
  {
    code: "operating.meals",
    nameEn: "Meals & Entertainment",
    nameEs: "Comidas y Entretenimiento",
    nameEl: "Γεύματα & Ψυχαγωγία",
    depth: 1,
    parentCode: "operating",
  },
  {
    code: "professional.accounting",
    nameEn: "Accounting & Legal",
    nameEs: "Contabilidad y Legal",
    nameEl: "Λογιστικά & Νομικά",
    depth: 1,
    parentCode: "professional",
  },
  {
    code: "professional.freelancer_fees",
    nameEn: "Freelancer / Contractor Fees",
    nameEs: "Honorarios Freelance",
    nameEl: "Αμοιβές Ελεύθ. Επαγγελματιών",
    depth: 1,
    parentCode: "professional",
  },
  {
    code: "technology.software",
    nameEn: "Software Subscriptions",
    nameEs: "Suscripciones Software",
    nameEl: "Συνδρομές Λογισμικού",
    depth: 1,
    parentCode: "technology",
  },
  {
    code: "technology.hardware",
    nameEn: "Hardware",
    nameEs: "Hardware",
    nameEl: "Υλικό (Hardware)",
    depth: 1,
    parentCode: "technology",
  },
  {
    code: "technology.hosting",
    nameEn: "Hosting & Cloud",
    nameEs: "Hosting y Cloud",
    nameEl: "Hosting & Cloud",
    depth: 1,
    parentCode: "technology",
  },
  {
    code: "travel.transport",
    nameEn: "Transportation",
    nameEs: "Transporte",
    nameEl: "Μεταφορές",
    depth: 1,
    parentCode: "travel",
  },
  {
    code: "travel.accommodation",
    nameEn: "Accommodation",
    nameEs: "Alojamiento",
    nameEl: "Διαμονή",
    depth: 1,
    parentCode: "travel",
  },
  {
    code: "travel.fuel",
    nameEn: "Fuel",
    nameEs: "Combustible",
    nameEl: "Καύσιμα",
    depth: 1,
    parentCode: "travel",
  },
  {
    code: "financial.bank_fees",
    nameEn: "Bank Fees",
    nameEs: "Comisiones Bancarias",
    nameEl: "Τραπεζικά Έξοδα",
    depth: 1,
    parentCode: "financial",
  },
  {
    code: "financial.interest",
    nameEn: "Interest Payments",
    nameEs: "Pagos de Intereses",
    nameEl: "Πληρωμές Τόκων",
    depth: 1,
    parentCode: "financial",
  },

  // Grandchild categories (depth 2)
  {
    code: "operating.utilities.electricity",
    nameEn: "Electricity",
    nameEs: "Electricidad",
    nameEl: "Ηλεκτρικό",
    depth: 2,
    parentCode: "operating.utilities",
  },
  {
    code: "operating.utilities.water",
    nameEn: "Water",
    nameEs: "Agua",
    nameEl: "Ύδρευση",
    depth: 2,
    parentCode: "operating.utilities",
  },
  {
    code: "operating.utilities.gas",
    nameEn: "Gas",
    nameEs: "Gas",
    nameEl: "Φυσικό Αέριο",
    depth: 2,
    parentCode: "operating.utilities",
  },
];
