import {
  pgTable,
  varchar,
  text,
  integer,
  boolean,
  timestamp,
} from "drizzle-orm/pg-core";

export const expenseGroups = pgTable("expense_group", {
  code: varchar("code", { length: 30 }).primaryKey(),
  nameEn: varchar("name_en", { length: 100 }).notNull(),
  nameEs: varchar("name_es", { length: 100 }),
  nameEl: varchar("name_el", { length: 100 }),
  nameDe: varchar("name_de", { length: 100 }),
  descriptionEn: text("description_en"),
  icon: varchar("icon", { length: 50 }),
  sortOrder: integer("sort_order").notNull().default(0),
  active: boolean("active").notNull().default(true),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export type ExpenseGroup = typeof expenseGroups.$inferSelect;
export type NewExpenseGroup = typeof expenseGroups.$inferInsert;

export const EXPENSE_GROUPS_SEED: NewExpenseGroup[] = [
  {
    code: "rent",
    nameEn: "Rent & Leasing",
    nameEs: "Alquiler y Leasing",
    nameEl: "Ενοίκιο & Leasing",
    nameDe: "Miete & Leasing",
    sortOrder: 1,
  },
  {
    code: "utilities",
    nameEn: "Utilities",
    nameEs: "Servicios",
    nameEl: "Κοινόχρηστα",
    nameDe: "Nebenkosten",
    sortOrder: 2,
  },
  {
    code: "telecom",
    nameEn: "Telecommunications",
    nameEs: "Telecomunicaciones",
    nameEl: "Τηλεπικοινωνίες",
    nameDe: "Telefon & Internet",
    sortOrder: 3,
  },
  {
    code: "office_supplies",
    nameEn: "Office Supplies & Materials",
    nameEs: "Material de oficina",
    nameEl: "Αναλώσιμα γραφείου",
    nameDe: "Büromaterial",
    sortOrder: 4,
  },
  {
    code: "software",
    nameEn: "Software & Subscriptions",
    nameEs: "Software y suscripciones",
    nameEl: "Λογισμικό & συνδρομές",
    nameDe: "Software & Abos",
    sortOrder: 5,
  },
  {
    code: "hardware",
    nameEn: "Hardware & Equipment",
    nameEs: "Equipos y hardware",
    nameEl: "Εξοπλισμός & hardware",
    nameDe: "Hardware & Geräte",
    sortOrder: 6,
  },
  {
    code: "professional_services",
    nameEn: "Professional Services",
    nameEs: "Servicios profesionales",
    nameEl: "Επαγγελματικές υπηρεσίες",
    nameDe: "Beratung & Buchhaltung",
    sortOrder: 7,
  },
  {
    code: "marketing",
    nameEn: "Marketing & Advertising",
    nameEs: "Marketing y publicidad",
    nameEl: "Διαφήμιση & marketing",
    nameDe: "Werbung & Marketing",
    sortOrder: 8,
  },
  {
    code: "travel",
    nameEn: "Travel",
    nameEs: "Viajes",
    nameEl: "Ταξίδια",
    nameDe: "Reisekosten",
    sortOrder: 9,
  },
  {
    code: "transport",
    nameEn: "Local Transport",
    nameEs: "Transporte",
    nameEl: "Μεταφορικά",
    nameDe: "Fahrtkosten",
    sortOrder: 10,
  },
  {
    code: "insurance",
    nameEn: "Insurance",
    nameEs: "Seguros",
    nameEl: "Ασφάλιστρα",
    nameDe: "Versicherungen",
    sortOrder: 11,
  },
  {
    code: "meals_entertainment",
    nameEn: "Meals & Entertainment",
    nameEs: "Comidas y entretenimiento",
    nameEl: "Γεύματα & φιλοξενία",
    nameDe: "Bewirtung",
    sortOrder: 12,
  },
  {
    code: "bank_fees",
    nameEn: "Bank & Financial Fees",
    nameEs: "Comisiones bancarias",
    nameEl: "Τραπεζικά έξοδα",
    nameDe: "Bankgebühren",
    sortOrder: 13,
  },
  {
    code: "training",
    nameEn: "Training & Education",
    nameEs: "Formación",
    nameEl: "Εκπαίδευση",
    nameDe: "Fortbildung",
    sortOrder: 14,
  },
  {
    code: "taxes_contributions",
    nameEn: "Taxes & Social Contributions",
    nameEs: "Impuestos y contribuciones",
    nameEl: "Φόροι & εισφορές",
    nameDe: "Steuern & Beiträge",
    sortOrder: 15,
  },
  {
    code: "other",
    nameEn: "Other Expenses",
    nameEs: "Otros gastos",
    nameEl: "Λοιπά έξοδα",
    nameDe: "Sonstige Ausgaben",
    sortOrder: 16,
  },
];
