import {
  pgTable,
  varchar,
  text,
  integer,
  boolean,
  timestamp,
  pgEnum,
} from "drizzle-orm/pg-core";

// Accounting classification for expense groups. Drives P&L grouping,
// VAT-report splits (input VAT on purchases vs. operating), and
// (future) GL-account routing. Applied universally — GAAP + IFRS
// agree on this COGS / OpEx / Asset / Other split.
export const expenseGroupTypeEnum = pgEnum("expense_group_type", [
  "operating_expense",
  "purchase",
  "asset",
  "other",
]);

export const expenseGroups = pgTable("expense_group", {
  code: varchar("code", { length: 30 }).primaryKey(),
  nameEn: varchar("name_en", { length: 100 }).notNull(),
  nameEs: varchar("name_es", { length: 100 }),
  nameEl: varchar("name_el", { length: 100 }),
  nameDe: varchar("name_de", { length: 100 }),
  descriptionEn: text("description_en"),
  icon: varchar("icon", { length: 50 }),
  sortOrder: integer("sort_order").notNull().default(0),
  active: boolean("active").notNull().default(true),
  type: expenseGroupTypeEnum("type").notNull().default("operating_expense"),
  typeColor: varchar("type_color", { length: 7 }),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export type ExpenseGroup = typeof expenseGroups.$inferSelect;
export type NewExpenseGroup = typeof expenseGroups.$inferInsert;
export type ExpenseGroupType = (typeof expenseGroupTypeEnum.enumValues)[number];

export const EXPENSE_GROUPS_SEED: NewExpenseGroup[] = [
  {
    code: "rent",
    nameEn: "Rent & Leasing",
    nameEs: "Alquiler y Leasing",
    nameEl: "Ενοίκιο & Leasing",
    nameDe: "Miete & Leasing",
    sortOrder: 1,
    type: "operating_expense",
  },
  {
    code: "utilities",
    nameEn: "Utilities",
    nameEs: "Servicios",
    nameEl: "Κοινόχρηστα",
    nameDe: "Nebenkosten",
    sortOrder: 2,
    type: "operating_expense",
  },
  {
    code: "telecom",
    nameEn: "Telecommunications",
    nameEs: "Telecomunicaciones",
    nameEl: "Τηλεπικοινωνίες",
    nameDe: "Telefon & Internet",
    sortOrder: 3,
    type: "operating_expense",
  },
  {
    code: "office_supplies",
    nameEn: "Office Supplies & Materials",
    nameEs: "Material de oficina",
    nameEl: "Αναλώσιμα γραφείου",
    nameDe: "Büromaterial",
    sortOrder: 4,
    type: "operating_expense",
  },
  {
    code: "software",
    nameEn: "Software & Subscriptions",
    nameEs: "Software y suscripciones",
    nameEl: "Λογισμικό & συνδρομές",
    nameDe: "Software & Abos",
    sortOrder: 5,
    type: "operating_expense",
  },
  {
    code: "hardware",
    nameEn: "Hardware & Equipment",
    nameEs: "Equipos y hardware",
    nameEl: "Εξοπλισμός & hardware",
    nameDe: "Hardware & Geräte",
    sortOrder: 6,
    type: "operating_expense",
  },
  {
    code: "professional_services",
    nameEn: "Professional Services",
    nameEs: "Servicios profesionales",
    nameEl: "Επαγγελματικές υπηρεσίες",
    nameDe: "Beratung & Buchhaltung",
    sortOrder: 7,
    type: "operating_expense",
  },
  {
    code: "marketing",
    nameEn: "Marketing & Advertising",
    nameEs: "Marketing y publicidad",
    nameEl: "Διαφήμιση & marketing",
    nameDe: "Werbung & Marketing",
    sortOrder: 8,
    type: "operating_expense",
  },
  {
    code: "travel",
    nameEn: "Travel",
    nameEs: "Viajes",
    nameEl: "Ταξίδια",
    nameDe: "Reisekosten",
    sortOrder: 9,
    type: "operating_expense",
  },
  {
    code: "transport",
    nameEn: "Local Transport",
    nameEs: "Transporte",
    nameEl: "Μεταφορικά",
    nameDe: "Fahrtkosten",
    sortOrder: 10,
    type: "operating_expense",
  },
  {
    code: "insurance",
    nameEn: "Insurance",
    nameEs: "Seguros",
    nameEl: "Ασφάλιστρα",
    nameDe: "Versicherungen",
    sortOrder: 11,
    type: "operating_expense",
  },
  {
    code: "meals_entertainment",
    nameEn: "Meals & Entertainment",
    nameEs: "Comidas y entretenimiento",
    nameEl: "Γεύματα & φιλοξενία",
    nameDe: "Bewirtung",
    sortOrder: 12,
    type: "operating_expense",
  },
  {
    code: "bank_fees",
    nameEn: "Bank & Financial Fees",
    nameEs: "Comisiones bancarias",
    nameEl: "Τραπεζικά έξοδα",
    nameDe: "Bankgebühren",
    sortOrder: 13,
    type: "operating_expense",
  },
  {
    code: "training",
    nameEn: "Training & Education",
    nameEs: "Formación",
    nameEl: "Εκπαίδευση",
    nameDe: "Fortbildung",
    sortOrder: 14,
    type: "operating_expense",
  },
  {
    code: "taxes_contributions",
    nameEn: "Taxes & Social Contributions",
    nameEs: "Impuestos y contribuciones",
    nameEl: "Φόροι & εισφορές",
    nameDe: "Steuern & Beiträge",
    sortOrder: 15,
    type: "other",
  },
  {
    code: "other",
    nameEn: "Other Expenses",
    nameEs: "Otros gastos",
    nameEl: "Λοιπά έξοδα",
    nameDe: "Sonstige Ausgaben",
    sortOrder: 16,
    type: "other",
  },
  // Universal to every country seed.
  {
    code: "salaries",
    nameEn: "Salaries",
    nameEs: "Salarios",
    nameEl: "Μισθοί",
    nameDe: "Gehälter",
    sortOrder: 17,
    type: "operating_expense",
  },
  {
    code: "employee_benefits",
    nameEn: "Employee Benefits",
    nameEs: "Beneficios para empleados",
    nameEl: "Παροχές εργαζομένων",
    nameDe: "Mitarbeiter-Leistungen",
    sortOrder: 18,
    type: "operating_expense",
  },
  {
    code: "repairs_maintenance",
    nameEn: "Repairs & Maintenance",
    nameEs: "Reparaciones y mantenimiento",
    nameEl: "Επισκευή & συντήρηση",
    nameDe: "Reparatur & Wartung",
    sortOrder: 19,
    type: "operating_expense",
  },
  {
    code: "purchases",
    nameEn: "Purchases & Inventory",
    nameEs: "Compras e inventario",
    nameEl: "Αγορές & απόθεμα",
    nameDe: "Einkäufe & Lager",
    sortOrder: 20,
    type: "purchase",
  },
];
